// images
import product1 from '../../../assets/images/products/product-1.png';
import product2 from '../../../assets/images/products/product-2.png';
import product3 from '../../../assets/images/products/product-3.png';
import product4 from '../../../assets/images/products/product-4.png';
import product5 from '../../../assets/images/products/product-5.png';
import product6 from '../../../assets/images/products/product-6.png';
import product7 from '../../../assets/images/products/product-7.png';
import product8 from '../../../assets/images/products/product-8.png';

import avatar1 from './../../../assets/images/users/avatar-4.jpg';
import avatar2 from './../../../assets/images/users/avatar-5.jpg';
import avatar3 from './../../../assets/images/users/avatar-6.jpg';
import avatar4 from './../../../assets/images/users/avatar-7.jpg';
import avatar5 from './../../../assets/images/users/avatar-8.jpg';
import avatar6 from './../../../assets/images/users/avatar-9.jpg';
import avatar7 from './../../../assets/images/users/avatar-10.jpg';
import avatar8 from './../../../assets/images/users/avatar-3.jpg';

export interface ProductItemTypes {
    id: number;
    product: string;
    image: string;
    category: string;
    added_date: string;
    rating: number;
    price: string;
    quantity: number;
    status: string;
}

export interface OrdersItemTypes {
    id: number;
    billing_name: string;
    order_id: string;
    order_date: string;
    order_time: string;
    payment_status: string;
    total: string;
    payment_method: string;
    order_status: string;
}

interface CustomersItemTypes {
    id: string;
    name: string;
    phone: string;
    balance: string;
    orders: number;
    last_order: string;
    avatar?: string;
    status: string;
}

export interface SellersItemTypes {
    id: number;
    name: string;
    store: string;
    products: number;
    balance: string;
    revenue: string;
    image?: string;
}

export interface CartItemTypes {
    id: number;
    image: string;
    name: string;
    size: string;
    color: string;
    price: number;
    qty: number;
    total: number;
}

const products: ProductItemTypes[] = [
    {
        id: 1,
        product: 'Blue color T-shirt',
        image: product1,
        rating: 4.9,
        category: 'T-shirt',
        added_date: '09 Mar, 2020',
        price: '$ 32',
        quantity: 112,
        status: 'Active',
    },
    {
        id: 2,
        product: 'Half sleeve maroon T-shirt',
        image: product2,
        rating: 3.1,
        category: 'T-shirt',
        added_date: '05 Mar, 2020',
        price: '$ 33',
        quantity: 60,
        status: 'Active',
    },
    {
        id: 3,
        product: 'Cream color T-shirt',
        image: product3,
        rating: 4.3,
        category: 'T-shirt',
        added_date: '02 Mar, 2020',
        price: '$ 33',
        quantity: 58,
        status: 'Deactive',
    },
    {
        id: 4,
        product: 'Blue color T-shirt',
        image: product4,
        rating: 4.9,
        category: 'T-shirt',
        added_date: '27 Feb, 2020',
        price: '$ 34',
        quantity: 98,
        status: 'Active',
    },
    {
        id: 5,
        product: 'Half sleeve T-shirt',
        image: product5,
        rating: 2.5,
        category: 'T-shirt',
        added_date: '23 Feb, 2020',
        price: '$ 35',
        quantity: 85,
        status: 'Deactive',
    },
    {
        id: 6,
        product: 'Blue Hoodie for men',
        image: product6,
        rating: 3.4,
        category: 'T-shirt',
        added_date: '21 Feb, 2020',
        price: '$ 36',
        quantity: 88,
        status: 'Active',
    },
    {
        id: 7,
        product: 'Vneck green T-shirt',
        image: product7,
        rating: 4.5,
        category: 'T-shirt',
        added_date: '19 Feb, 2020',
        price: '$ 37',
        quantity: 82,
        status: 'Active',
    },
    {
        id: 8,
        product: 'Full sleeve Pink T-shirt',
        image: product8,
        rating: 2.4,
        category: 'T-shirt',
        added_date: '15 Feb, 2020',
        price: '$ 38',
        quantity: 54,
        status: 'Active',
    },
    {
        id: 9,
        product: 'Blue color T-shirt',
        image: product1,
        rating: 4.3,
        category: 'T-shirt',
        added_date: '15 Feb, 2020',
        price: '$ 38',
        quantity: 60,
        status: 'Active',
    },
    {
        id: 10,
        product: 'Half sleeve maroon T-shirt',
        image: product2,
        rating: 4.0,
        category: 'T-shirt',
        added_date: '13 Feb, 2020',
        price: '$ 45',
        quantity: 32,
        status: 'Deactive',
    },
    {
        id: 11,
        product: 'Cream color T-shirt',
        image: product3,
        rating: 4.2,
        category: 'T-shirt',
        added_date: '12 Feb, 2020',
        price: '$ 46',
        quantity: 64,
        status: 'Active',
    },
    {
        id: 12,
        product: 'Blue color T-shirt',
        image: product4,
        rating: 4.0,
        category: 'T-shirt',
        added_date: '08 Feb, 2020',
        price: '$ 47',
        quantity: 74,
        status: 'Deactive',
    },
];

const orders: OrdersItemTypes[] = [
    {
        id: 1,
        billing_name: 'James Modlin',
        order_id: '31',
        order_date: 'Apr 16 2020',
        order_time: '1:45 PM',
        payment_status: 'Payment Failed',
        total: '$8361.93',
        payment_method: 'Visa',
        order_status: 'Processing',
    },
    {
        id: 2,
        billing_name: 'Lessie Craig',
        order_id: '060',
        order_date: 'Apr 15 2020',
        order_time: '12:10 PM',
        payment_status: 'Unpaid',
        total: '$6219.67',
        payment_method: 'Credit Card',
        order_status: 'Shipped',
    },
    {
        id: 3,
        billing_name: 'Tia McCord',
        order_id: '76961',
        order_date: 'Apr 14 2020',
        order_time: '2:53 AM',
        payment_status: 'Payment Failed',
        total: '$6695.83',
        payment_method: 'Paypal',
        order_status: 'Shipped',
    },
    {
        id: 4,
        billing_name: 'Charles Wilson',
        order_id: '59',
        order_date: 'Mar 13 2020',
        order_time: '2:53 AM',
        payment_status: 'Paid',
        total: '$8616.73',
        payment_method: 'Visa',
        order_status: 'Delivered',
    },
    {
        id: 5,
        billing_name: 'Kathryn McCann',
        order_id: '93',
        order_date: 'Mar 12 2020',
        order_time: '1:52 PM',
        payment_status: 'Awaiting Authorization',
        total: '$1808.61',
        payment_method: 'Paypal',
        order_status: 'Shipped',
    },
    {
        id: 6,
        billing_name: 'William Eckert',
        order_id: '2164',
        order_date: 'Mar 11 2020',
        order_time: '3:59 AM',
        payment_status: 'Paid',
        total: '$9813.57',
        payment_method: 'Paypal',
        order_status: 'Delivered',
    },
    {
        id: 7,
        billing_name: 'Julius West',
        order_id: '22410',
        order_date: 'Mar 10 2020',
        order_time: '7:29 AM',
        payment_status: 'Awaiting Authorization',
        total: '$9457.23',
        payment_method: 'Mastercard',
        order_status: 'Delivered',
    },
    {
        id: 8,
        billing_name: 'Janice Louie',
        order_id: '04260',
        order_date: 'Feb 09 2020',
        order_time: '5:14 AM',
        payment_status: 'Unpaid',
        total: '$1054.76',
        payment_method: 'Payoneer',
        order_status: 'Processing',
    },
    {
        id: 9,
        billing_name: 'Marie Harris',
        order_id: '77',
        order_date: 'Feb 08 2020',
        order_time: '9:34 AM',
        payment_status: 'Payment Failed',
        total: '$3526.87',
        payment_method: 'Payoneer',
        order_status: 'Shipped',
    },
    {
        id: 10,
        billing_name: 'Robin Hill',
        order_id: '938',
        order_date: 'Jan 07 2020',
        order_time: '6:16 PM',
        payment_status: 'Paid',
        total: '$8201.67',
        payment_method: 'Paypal',
        order_status: 'Delivered',
    },
    {
        id: 11,
        billing_name: 'Julius West',
        order_id: '99',
        order_date: 'Mar 11 2020',
        order_time: '11:23 PM',
        payment_status: 'Payment Failed',
        total: '$9557.76',
        payment_method: 'Paypal',
        order_status: 'Processing',
    },
    {
        id: 12,
        billing_name: 'Lessie Craig',
        order_id: '397',
        order_date: 'Mar 20 2020',
        order_time: '11:18 PM',
        payment_status: 'Unpaid',
        total: '$8391.95',
        payment_method: 'Visa',
        order_status: 'Processing',
    },
    {
        id: 13,
        billing_name: 'Janice Louie',
        order_id: '4874',
        order_date: 'Apr 15 2020',
        order_time: '2:15 PM',
        payment_status: 'Unpaid',
        total: '$3558.36',
        payment_method: 'Paypal',
        order_status: 'Cancelled',
    },
    {
        id: 14,
        billing_name: 'Lessie Craig',
        order_id: '496',
        order_date: 'Apr 16 2020',
        order_time: '7:56 PM',
        payment_status: 'Payment Failed',
        total: '$2871.99',
        payment_method: 'Credit Card',
        order_status: 'Delivered',
    },
    {
        id: 15,
        billing_name: 'James Modlin',
        order_id: '982',
        order_date: 'Apr 15 2020',
        order_time: '7:54 PM',
        payment_status: 'Awaiting Authorization',
        total: '$415.59',
        payment_method: 'Mastercard',
        order_status: 'Processing',
    },
    {
        id: 16,
        billing_name: 'Lessie Craig',
        order_id: '66303',
        order_date: 'Apr 14 2020',
        order_time: '10:47 AM',
        payment_status: 'Paid',
        total: '$9554.21',
        payment_method: 'Credit Card',
        order_status: 'Shipped',
    },
    {
        id: 17,
        billing_name: 'Tia McCord',
        order_id: '73',
        order_date: 'Mar 13 2020',
        order_time: '4:24 PM',
        payment_status: 'Payment Failed',
        total: '$9766.71',
        payment_method: 'Mastercard',
        order_status: 'Delivered',
    },
    {
        id: 18,
        billing_name: 'Charles Wilson',
        order_id: '90804',
        order_date: 'Mar 12 2020',
        order_time: '5:42 PM',
        payment_status: 'Payment Failed',
        total: '$1194.25',
        payment_method: 'Mastercard',
        order_status: 'Cancelled',
    },
    {
        id: 19,
        billing_name: 'Kathryn McCann',
        order_id: '97489',
        order_date: 'Mar 11 2020',
        order_time: '11:47 PM',
        payment_status: 'Paid',
        total: '$8715.09',
        payment_method: 'Visa',
        order_status: 'Processing',
    },
    {
        id: 20,
        billing_name: 'William Eckert',
        order_id: '53577',
        order_date: 'Mar 10 2020',
        order_time: '8:47 PM',
        payment_status: 'Unpaid',
        total: '$2836.42',
        payment_method: 'Mastercard',
        order_status: 'Delivered',
    },
    {
        id: 21,
        billing_name: 'Julius West',
        order_id: '8940',
        order_date: 'Feb 09 2020',
        order_time: '6:14 PM',
        payment_status: 'Paid',
        total: '$3552.93',
        payment_method: 'Credit Card',
        order_status: 'Delivered',
    },
    {
        id: 22,
        billing_name: 'Janice Louie',
        order_id: '34334',
        order_date: 'Feb 08 2020',
        order_time: '7:19 PM',
        payment_status: 'Payment Failed',
        total: '$7487.68',
        payment_method: 'Payoneer',
        order_status: 'Delivered',
    },
    {
        id: 23,
        billing_name: 'Marie Harris',
        order_id: '2',
        order_date: 'Jan 07 2020',
        order_time: '4:29 AM',
        payment_status: 'Paid',
        total: '$2900.64',
        payment_method: 'Mastercard',
        order_status: 'Delivered',
    },
    {
        id: 24,
        billing_name: 'Robin Hill',
        order_id: '478',
        order_date: 'Apr 15 2020',
        order_time: '9:29 AM',
        payment_status: 'Unpaid',
        total: '$7589.76',
        payment_method: 'Visa',
        order_status: 'Delivered',
    },
    {
        id: 25,
        billing_name: 'Tia McCord',
        order_id: '95',
        order_date: 'Mar 30 2020',
        order_time: '9:47 AM',
        payment_status: 'Unpaid',
        total: '$3774.83',
        payment_method: 'Mastercard',
        order_status: 'Delivered',
    },
    {
        id: 26,
        billing_name: 'Charles Wilson',
        order_id: '160',
        order_date: 'Apr 15 2020',
        order_time: '1:39 PM',
        payment_status: 'Paid',
        total: '$2696.43',
        payment_method: 'Paypal',
        order_status: 'Cancelled',
    },
    {
        id: 27,
        billing_name: 'Kathryn McCann',
        order_id: '81338',
        order_date: 'Feb 08 2020',
        order_time: '4:59 PM',
        payment_status: 'Unpaid',
        total: '$4720.65',
        payment_method: 'Credit Card',
        order_status: 'Processing',
    },
    {
        id: 28,
        billing_name: 'William Eckert',
        order_id: '75',
        order_date: 'Apr 16 2020',
        order_time: '10:24 AM',
        payment_status: 'Unpaid',
        total: '$7674.74',
        payment_method: 'Visa',
        order_status: 'Delivered',
    },
    {
        id: 29,
        billing_name: 'Julius West',
        order_id: '8',
        order_date: 'Apr 15 2020',
        order_time: '5:08 AM',
        payment_status: 'Paid',
        total: '$2399.90',
        payment_method: 'Paypal',
        order_status: 'Delivered',
    },
    {
        id: 30,
        billing_name: 'Janice Louie',
        order_id: '99',
        order_date: 'Apr 14 2020',
        order_time: '1:33 AM',
        payment_status: 'Payment Failed',
        total: '$2471.31',
        payment_method: 'Visa',
        order_status: 'Cancelled',
    },
    {
        id: 31,
        billing_name: 'Marie Harris',
        order_id: '976',
        order_date: 'Mar 13 2020',
        order_time: '8:21 AM',
        payment_status: 'Unpaid',
        total: '$8073.28',
        payment_method: 'Visa',
        order_status: 'Processing',
    },
    {
        id: 32,
        billing_name: 'Robin Hill',
        order_id: '13',
        order_date: 'Mar 12 2020',
        order_time: '5:41 AM',
        payment_status: 'Unpaid',
        total: '$4393.62',
        payment_method: 'Payoneer',
        order_status: 'Cancelled',
    },
    {
        id: 33,
        billing_name: 'James Modlin',
        order_id: '8333',
        order_date: 'Mar 11 2020',
        order_time: '4:42 AM',
        payment_status: 'Paid',
        total: '$6077.15',
        payment_method: 'Paypal',
        order_status: 'Cancelled',
    },
    {
        id: 34,
        billing_name: 'Lessie Craig',
        order_id: '21547',
        order_date: 'Mar 10 2020',
        order_time: '8:42 PM',
        payment_status: 'Unpaid',
        total: '$5792.53',
        payment_method: 'Mastercard',
        order_status: 'Processing',
    },
    {
        id: 35,
        billing_name: 'Tia McCord',
        order_id: '25',
        order_date: 'Feb 09 2020',
        order_time: '10:38 PM',
        payment_status: 'Payment Failed',
        total: '$8661.65',
        payment_method: 'Credit Card',
        order_status: 'Cancelled',
    },
    {
        id: 36,
        billing_name: 'Charles Wilson',
        order_id: '3201',
        order_date: 'Feb 08 2020',
        order_time: '9:57 PM',
        payment_status: 'Payment Failed',
        total: '$7795.53',
        payment_method: 'Visa',
        order_status: 'Processing',
    },
    {
        id: 37,
        billing_name: 'Kathryn McCann',
        order_id: '797',
        order_date: 'Jan 07 2020',
        order_time: '9:53 PM',
        payment_status: 'Paid',
        total: '$9755.20',
        payment_method: 'Mastercard',
        order_status: 'Cancelled',
    },
    {
        id: 38,
        billing_name: 'William Eckert',
        order_id: '7078',
        order_date: 'Feb 08 2020',
        order_time: '9:09 AM',
        payment_status: 'Unpaid',
        total: '$2335.70',
        payment_method: 'Mastercard',
        order_status: 'Processing',
    },
    {
        id: 39,
        billing_name: 'Julius West',
        order_id: '4380',
        order_date: 'Mar 13 20209',
        order_time: '5:33 AM',
        payment_status: 'Awaiting Authorization',
        total: '$1342.74',
        payment_method: 'Paypal',
        order_status: 'Shipped',
    },
    {
        id: 40,
        billing_name: 'Janice Louie',
        order_id: '4',
        order_date: 'Apr 16 2020',
        order_time: '11:35 AM',
        payment_status: 'Paid',
        total: '$626.28',
        payment_method: 'Payoneer',
        order_status: 'Delivered',
    },
    {
        id: 41,
        billing_name: 'James Modlin',
        order_id: '54',
        order_date: 'Apr 15 2020',
        order_time: '1:51 AM',
        payment_status: 'Unpaid',
        total: '$1903.55',
        payment_method: 'Visa',
        order_status: 'Processing',
    },
    {
        id: 42,
        billing_name: 'Lessie Craig',
        order_id: '6084',
        order_date: 'Apr 14 2020',
        order_time: '11:08 AM',
        payment_status: 'Unpaid',
        total: '$1671.64',
        payment_method: 'Paypal',
        order_status: 'Delivered',
    },
    {
        id: 43,
        billing_name: 'Tia McCord',
        order_id: '7004',
        order_date: 'Mar 13 2020',
        order_time: '6:18 AM',
        payment_status: 'Payment Failed',
        total: '$7471.41',
        payment_method: 'Payoneer',
        order_status: 'Shipped',
    },
    {
        id: 44,
        billing_name: 'Charles Wilson',
        order_id: '00890',
        order_date: 'Mar 12 2020',
        order_time: '5:36 AM',
        payment_status: 'Payment Failed',
        total: '$7395.11',
        payment_method: 'Paypal',
        order_status: 'Processing',
    },
    {
        id: 45,
        billing_name: 'Robin Hill',
        order_id: '60931',
        order_date: 'Mar 11 2020',
        order_time: '11:31 PM',
        payment_status: 'Awaiting Authorization',
        total: '$4022.17',
        payment_method: 'Payoneer',
        order_status: 'Delivered',
    },
    {
        id: 46,
        billing_name: 'James Modlin',
        order_id: '2',
        order_date: 'Mar 10 2020',
        order_time: '1:01 PM',
        payment_status: 'Payment Failed',
        total: '$7455.30',
        payment_method: 'Payoneer',
        order_status: 'Shipped',
    },
    {
        id: 47,
        billing_name: 'Lessie Craig',
        order_id: '92',
        order_date: 'Feb 09 2020',
        order_time: '2:48 PM',
        payment_status: 'Unpaid',
        total: '$192.21',
        payment_method: 'Visa',
        order_status: 'Delivered',
    },
    {
        id: 48,
        billing_name: 'Tia McCord',
        order_id: '937',
        order_date: 'Feb 08 2020',
        order_time: '6:06 PM',
        payment_status: 'Payment Failed',
        total: '$4070.53',
        payment_method: 'Visa',
        order_status: 'Shipped',
    },
    {
        id: 49,
        billing_name: 'Charles Wilson',
        order_id: '3474',
        order_date: 'Jan 07 2020',
        order_time: '8:18 PM',
        payment_status: 'Unpaid',
        total: '$2957.29',
        payment_method: 'Visa',
        order_status: 'Cancelled',
    },
    {
        id: 50,
        billing_name: 'Kathryn McCann',
        order_id: '1419',
        order_date: 'Mar 11 2020',
        order_time: '12:58 AM',
        payment_status: 'Unpaid',
        total: '$8052.46',
        payment_method: 'Mastercard',
        order_status: 'Shipped',
    },
];

const customers: CustomersItemTypes[] = [
    {
        id: '#MN2048',
        name: 'Paul J. Friend',
        phone: '050 414 8778',
        balance: '$12,874.82',
        orders: 43,
        last_order: '02 Apr, 2020',
        avatar: avatar1,
        status: 'Active',
    },
    {
        id: '#MN2047',
        name: 'Bryan J. Luellen',
        phone: '215-302-3376',
        balance: '$874.25',
        orders: 220,
        last_order: '04 Mar, 2020',
        avatar: avatar2,
        status: 'Active',
    },
    {
        id: '#MN2046',
        name: 'Kathryn S. Collier',
        phone: '828-216-2190',
        balance: '$125.78',
        orders: 841,
        last_order: '11 Jul, 2020',
        status: 'Blocked',
    },
    {
        id: '#MN2045',
        name: 'Timothy Kauper',
        phone: '(216) 75 612 706',
        balance: '$561.25',
        orders: 62,
        last_order: '15 Nov, 2020',
        avatar: avatar5,
        status: 'Blocked',
    },
    {
        id: '#MN2044',
        name: 'Zara Raws',
        phone: '(02) 75 150 655',
        balance: '$2147.84',
        orders: 9,
        last_order: '21 Feb, 2020',
        status: 'Active',
    },
    {
        id: '#MN2043',
        name: 'Annette P. Kelsch',
        phone: '(+15) 73 483 758',
        balance: '$451.28',
        orders: 25,
        last_order: '12 Jun, 2020',
        avatar: avatar1,
        status: 'Active',
    },
    {
        id: '#MN2042',
        name: 'Jenny C. Gero',
        phone: '078 7173 9261',
        balance: '$965.20',
        orders: 214,
        last_order: '14 Jul, 2020',
        status: 'Blocked',
    },
    {
        id: '#MN2041',
        name: 'Edward Roseby',
        phone: '078 6013 3854',
        balance: '$71584.2',
        orders: 365,
        last_order: '16 Aug, 2020',
        avatar: avatar3,
        status: 'Active',
    },
    {
        id: '#MN2040',
        name: 'Anna Ciantar',
        phone: '(216) 76 298 896',
        balance: '$5482.00',
        orders: 921,
        last_order: '13 Sep, 2020',
        avatar: avatar6,
        status: 'Active',
    },
    {
        id: '#MN2039',
        name: 'Dean Smithies',
        phone: '077 6157 4248',
        balance: '$482.15',
        orders: 68,
        last_order: '18 Nov, 2020',
        avatar: avatar7,
        status: 'Active',
    },
    {
        id: '#MN2038',
        name: 'Labeeb Ghali',
        phone: '050 414 8778',
        balance: '$7852.3',
        orders: 475,
        last_order: '14 Apr, 2020',
        avatar: avatar2,
        status: 'Active',
    },
    {
        id: '#MN2037',
        name: 'Rory Seekamp',
        phone: '078 5054 8877',
        balance: '$3365.12',
        orders: 25,
        last_order: '21 Dec, 2020',
        avatar: avatar4,
        status: 'Blocked',
    },
];

const sellers: SellersItemTypes[] = [
    {
        id: 1,
        name: 'Charles Garcia',
        store: 'Homovee',
        products: 125,
        balance: '$126,562',
        revenue: '$235.16k',
    },
    {
        id: 2,
        name: 'Nicholas Watkins',
        store: 'Execucy',
        products: 125,
        balance: '$84,235',
        revenue: '$196.08k',
        image: avatar8,
    },
    {
        id: 3,
        name: 'Jared Carroll',
        store: 'Epiloo',
        products: 96,
        balance: '$124,250',
        revenue: '$201.04k',
    },
    {
        id: 4,
        name: 'Gregory Secrest',
        store: 'Uberer',
        products: 84,
        balance: '$74,236',
        revenue: '$175.12k',
    },
    {
        id: 5,
        name: 'Leticia Cane',
        store: 'Symic',
        products: 134,
        balance: '$92,237',
        revenue: '$172.24k',
        image: avatar1,
    },
    {
        id: 6,
        name: 'Tyler Smith',
        store: 'Vicedel',
        products: 56,
        balance: '$57,235',
        revenue: '$162.52k',
        image: avatar2,
    },
];

const cartItems: CartItemTypes[] = [
    {
        id: 1,
        image: product1,
        name: 'Blue color T-shirt',
        size: 'Large',
        color: 'Light Green',
        price: 41,
        qty: 2,
        total: 92,
    },
    {
        id: 2,
        image: product2,
        name: 'Half sleeve maroon T-shirt',
        size: 'Small',
        color: 'Brown',
        price: 37,
        qty: 1,
        total: 37,
    },
    {
        id: 3,
        image: product6,
        name: 'Blue Hoodie for men',
        size: 'Medium',
        color: 'Light pink',
        price: 45,
        qty: 2,
        total: 90,
    },
    {
        id: 4,
        image: product8,
        name: 'Full sleeve Pink T-shirt',
        size: 'Large',
        color: 'Green',
        price: 45,
        qty: 1,
        total: 45,
    },
];

export { products, orders, customers, sellers, cartItems };
